### ISSUE TITLE
Using docker-smf with Win7 Docker Toolbox

### ISSUE THREAD

**Issue by bhutten14** [Eeems/docker-smf#1]
Hi,

I'm using Win7 and Docker Toolbox. I try to spin-up the container, which basically succeeds. I used the following docker-compose.yml:
version: '3'
services:
  smf:
    container_name: smf
    image: eeems/smf
    ports:
      - "8500:80"
    environment:
      - SMF_BOARD_URL=http://192.168.99.100:8500/

But when looking in the browser there is no theme. So it seems to work fine, only the layout is bad. Does anybody ran this container with Docker Toolbox?

**Comment by Eeems** [comment]
@bhutten14 have you checked the browsers console to see why the theme is failing to load?

**Comment by bhutten14** [comment]
What I found out is that when I go to Admin -> Configuration -> Server Settings -> Database and Paths, and then change the setting **`Forum URL`**, from `http://192.168.99.100:8500` to `http://192.168.99.100:8500/`, it all works fine.

**Comment by Eeems** [comment]
That is interesting. In start.sh I'm ensuring that the URL ends with a slash ([start.sh line 4](https://github.com/Eeems/docker-smf/blob/master/start.sh#L4)). I'm not sure where it's losing that slash, unless that is something that repair_settings.php is doing.
I would suggest you add some extra logging to start.sh and see if it's losing the slash in your environment.

**Comment by Eeems** [comment]
@ultranoobian Am I correct in understanding that you are also encountering this? If so, can modify start.sh to echo into a file and take a look at what `repair_settings.php` is returning?

**Comment by ultranoobian** [comment]
@Eeems This may or may not be what you what. If not, tell me how you want it.

https://gist.github.com/ultranoobian/1b992d3bbe98ca972e5307f40f59ab90

**Comment by Eeems** [comment]
That is useful, it's giving me the following error message:

> Some settings are not being shown because the database connection information is incorrect.
> Check your database login details, table prefix and that the database actually contains your SMF tables.

Based on the Dockerfile, the username/db/password should be correct (smf/root/rootpass). Have you modified it at all?

**Comment by ultranoobian** [comment]
No, it is a clean clone of the current e8d8913 master (excluding the extra logging in start.sh)

This is the [settings.php](https://gist.github.com/ultranoobian/3bacdc18f64eea37f835199ca0c110fb) in /var/www/smf 

Edit: When I run/login to mysql with (root:rootpass) inside the container, there are meant to be tables there right?

```mysql --user=root --password smf
show tables; // Empty Set (0.000 sec)
```

**Comment by Eeems** [comment]
Yes there should be tables in the smf database. Could you do some extra logging of the dockerfile build to see what is failing there?

**Comment by ultranoobian** [comment]
@Eeems This is the only useful information I could really get from the dockerfile https://gist.github.com/ultranoobian/e5fc0f5bc36ea39731886eba6c6c7fce

I can't make much sense of it, but it looks like something goes wrong in the first step of the install.php page?

**Comment by Eeems** [comment]
The error I'm seeing in the log is
> Uncaught Error: Call to undefined function db_fatal_error()

Which means there is an underlying error that is actually being thrown that isn't being reported. This is happening while trying to install SMF into the database. I wonder if the database hasn't finished starting properly or an issue happened in an earlier step. Can you try building without the case so we can see what happened in steps 3-6?

**Comment by Eeems** [comment]
Alright, I was able to reproduce this by updating my php:7.1-apache base image. I've fix the issue and pushed up a new version to dockerhub.

**Comment by ultranoobian** [comment]
Any explanation on why it didn't want to work?
